name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Copy your upcoming page as index.html so GitHub Pages shows it
      - name: Set homepage
        run: cp upcoming.html index.html

      # Ensure CNAME is included for custom domain
      - name: Create CNAME file
        run: echo "gauravthakur.space" > CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
